spring:
  autoconfigure:
    exclude:
      ## Temporary due Cassandra issues
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
  task:
    scheduling:
      pool:
        size: 2
  jackson:
    time-zone: America/Sao_Paulo
  config:
    activate:
      on-profile: default
  application:
    name: spotify-top-k-songs-consumer

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: MANUAL
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: kafka-app-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.interval.ms: 30000
        request.timeout.ms: 10000
        session.timeout.ms: 10000
        fetch.min.bytes: 1
        fetch.max.wait.ms: 500
        max.poll.records: 50
        heartbeat.interval.ms: 3000

  data:
    cassandra:
      keyspace-name: spotify_keyspace
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS
      session-name: spotify-session

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true

# Custom properties (if needed) - these can stay at root level
kafka:
  topics:
    songs-listened: songs-listened-topic